apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master # 名前の指定（必須）
spec:
  replicas: 1 # コンテナのレプリカ数の設定
  template:
    metadata:
      labels: # ラベルをKV型で設定
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master # コンテナの名前
        image: gcr.io/google_containers/redis:e2e # コンテナイメージの指定（必須）
        resources:
          requests:
            cpu: 100m # CPUを0.1コア確保
            memory: 100Mi # メモリ100MiB確保
        ports:
        - containerPort: 6379 # コンテナポートの指定
